version: "3"
services:
  rails:
    container_name: rails-sandbox-rails
    build: .
    env_file: .env
    volumes:
    - .:/app
    - bundle:/usr/local/bundle
    - node_modules:/app/node_modules
    ports:
    - 3000:3000
  webpacker:
    container_name: rails-sandbox-webpacker
    build:
      context: .
      dockerfile: ./etc/docker/webpacker/Dockerfile
    env_file: .env
    volumes:
    - .:/app
    - bundle:/usr/local/bundle
    - node_modules:/app/node_modules
    ports:
    - 3035:3035
volumes:
  bundle:
  node_modules:
